#coding=utf-8
#E:\Python34\Lib\site-packages\selenium\webdriver
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time
import os
if __name__ == '__main__':
    driver = webdriver.Ie() 
    print("open IE explorer")
    #web='http://ccmssit/clv'
    url='http://99.48.237.32/CCPCLVBH.SIT/WorkList.aspx?id=&expandIndex=0'
    driver.get(url)
    driver.maximize_window()
    time.sleep(3)
    driver.switch_to_window(driver.current_window_handle)
    print ("title of current page is %s" %(driver.title))
    print ("url of current page is %s" %(driver.current_url))
    # assert "招商银行信用卡中心" in driver.文本
    username = driver.find_element_by_name("txtUserName")
    pwd =driver.find_element_by_name("txtPassword")
    login=driver.find_element_by_name("btnLogin")
    username.send_keys("043985")
    time.sleep(2)
    print('username input:043985')
    pwd.send_keys("111")
    time.sleep(2)
    print('pwd input:111')
    login.click()
    time.sleep(5)
    print('loginOn')
    driver.find_element_by_id('ctl00_accordion_Pane_1_header').click()
    time.sleep(2)
    print('baobiaochakan')
    driver.find_element_by_id('ctl00_accordion_Pane_0_header').click()
    time.sleep(2)
    print('wodegongzuo')
    driver.find_element_by_link_text('待审件客户查询').click()
    time.sleep(5)
    highchoice=driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_btnPro')
    time.sleep(2)
    highchoice.click()
    driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_txtBeginDate').clear()
    time.sleep(2)
    driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_txtBeginDate').send_keys('2014-01-11')
    time.sleep(2)
    
    cutname=driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_txtName')
    cutname.send_keys("常萍")
    time.sleep(2)
    driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_ddlApplicationType').find_elements_by_tag_name('option')[0].click()
    driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_ddlNewCard').find_elements_by_tag_name('option')[1].click()
    #lingyongheyue=driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_txtNo')
    #lingyongheyue.send_keys("5186908812")
    query=driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_btnSearch')
    query.click()
    time.sleep(2)
    alert = driver.switch_to_alert()
    print (alert.text)
    alert.accept()
    print('databeyond')
    print('query successful')
    handle1=driver.current_window_handle
    handles = driver.window_handles
    print(handles)
    for handle1 in handles:
    #print(handle1)
      driver.switch_to_window(handle1)
    print ("title of current page is %s" %(driver.title))
    print ("url of current page is %s" %(driver.current_url))
    driver.find_element_by_link_text('推广日期').click()
    time.sleep(2)
    driver.find_element_by_link_text('推广日期').click()
    time.sleep(2)
    driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_gvWorklist_ctl23_btnNext').click()
    time.sleep(3)
    print('nextpage')
    sousuokuang=driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_gvWorklist_ctl23_txtNewPageIndex')
    sousuokuang.clear()
    time.sleep(2)
    sousuokuang.send_keys('1')
    time.sleep(2)
    driver.find_element_by_id('ctl00_DefaultContentPlaceHolder_gvWorklist_ctl23_btnGo').click()
    time.sleep(2)    
    chuli=driver.find_element_by_link_text('处理')
    chuli.click()
    time.sleep(10)
    print('chulistart')
    handle2=driver.current_window_handle
    handles = driver.window_handles
    print(handles)
    for handle2 in handles:
    #print(handle1)
      driver.switch_to_window(handle2)
    print ("title of current page is %s" %(driver.title))
    print ("url of current page is %s" %(driver.current_url))
    shenqingxinxi=driver.find_element_by_id('__tab_TabContainerMain_TabPanelContent')
    shenqingxinxi.click()
    time.sleep(2)
    shenhejilu=driver.find_element_by_id('__tab_TabContainerMain_TabPanelLog')
    shenhejilu.click()
    time.sleep(2)
    chushen=driver.find_element_by_id('__tab_TabContainerMain_TabPanelIdentity')
    chushen.click()
    time.sleep(2)
    fuhexiang=driver.find_element_by_id('chkReAudit_0')
    fuhexiang.click()
    time.sleep(2)   
    shenhebeizhu=driver.find_element_by_id('txtAuditMemo')
    shenhebeizhu.send_keys('123321')
    print('inputbiezhu')
    time.sleep(2)
    jmsh=driver.find_element_by_id('chkAuditMode_0')
    jmsh.click()
    time.sleep(2)
    driver.find_element_by_id('ddlApplicationType').find_elements_by_tag_name('option')[0].click()
    tongguo=driver.find_element_by_id('btnPass')
    tongguo.click()
    
    alert = driver.switch_to_alert()
    print (alert.text)
    alert.accept()
    time.sleep(2)
    alert = driver.switch_to_alert()
    print (alert.text)
    alert.accept()
    driver.close()
    driver.quit()
